const TenderData = [
  {
    id: 1,
    title: 'Buta Grup',
    // image: '',
    header: 'Buta Grup Veb saytın yaradılması üçün tender elan edir',
    feedbacks: {
      green: 0,
      red: 0,
      blue: 0,
    },
    price: 0,
    addedDate: 9,
    deadLine: '13.04.2021',
    order: 0,
  },
  {
    id: 2,
    title: 'Buta Grup',
    // image: '',
    header: 'Buta Grup Dizayn hazirlanmasi üçün tender elan edir',
    feedbacks: {
      green: 0,
      red: 0,
      blue: 0,
    },
    price: 0,
    addedDate: 2,
    deadLine: '11.05.2021',
    order: 0,
  },
  {
    id: 3,
    title: 'Buta Grup',
    // image: '',
    header: 'Buta Grup Dizayn hazirlanmasi üçün tender elan edir',
    feedbacks: {
      green: 0,
      red: 0,
      blue: 0,
    },
    price: 0,
    addedDate: 2,
    deadLine: '11.05.2021',
    order: 0,
  },
  {
    id: 4,
    title: 'Buta Grup',
    // image: '',
    header: 'Buta Grup Dizayn hazirlanmasi üçün tender elan edir',
    feedbacks: {
      green: 0,
      red: 0,
      blue: 0,
    },
    price: 0,
    addedDate: 2,
    deadLine: '11.05.2021',
    order: 0,
  },
  {
    id: 5,
    title: 'Buta Grup',
    // image: '',
    header: 'Buta Grup Dizayn hazirlanmasi üçün tender elan edir',
    feedbacks: {
      green: 0,
      red: 0,
      blue: 0,
    },
    price: 0,
    addedDate: 2,
    deadLine: '11.05.2021',
    order: 0,
  },
];

export default TenderData;
